### ISSUE TITLE
[BUG] opensearch-hadoop throws OpenSearchHadoopIllegalArgumentException with AWS OpenSearch service running OpenSearch Engine 2.3

### ISSUE THREAD

**Issue by prashantsc** [opensearch-project/opensearch-hadoop#164]
I have AWS OpenSearch Service with OpenSearch Engine 2.3. It has compatible mode ON to return the version 7.10.2 as mentioned in below snippet.  And, I am using opensearch-hadoop with Spark 3.0 Scala. 2.12 in AWS Glue env. 
conf: opensearch.nodes.wan.only=false.

`{
  "name" : "----",
  "cluster_name" : "----",
  "cluster_uuid" : "----",
  "version" : {
    "number" : "7.10.2",
    "build_type" : "tar",
    "build_hash" : "unknown",
    "build_date" : "2023-02-03T05:10:56.808891Z",
    "build_snapshot" : false,
    "lucene_version" : "9.3.0",
    "minimum_wire_compatibility_version" : "7.10.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
`

With above setup I am get following error: 
` ERROR [main] glue.ProcessLauncher (Logging.scala:logError(94)): Exception in User Class
org.opensearch.hadoop.OpenSearchHadoopIllegalArgumentException: Cannot detect OpenSearch version - typically this happens if the network/OpenSearch cluster is not accessible or when targeting a WAN/Cloud instance without the proper setting 'opensearch.nodes.wan.only'
	at org.opensearch.hadoop.rest.InitializationUtils.discoverClusterInfo(InitializationUtils.java:440)
	at org.opensearch.spark.sql.OpenSearchSparkSQL$.saveToOpenSearch(OpenSearchSparkSQL.scala:109)
	at org.opensearch.spark.sql.OpenSearchSparkSQL$.saveToOpenSearch(OpenSearchSparkSQL.scala:91)
	at org.opensearch.spark.sql.package$SparkDataFrameFunctions.saveToOpenSearch(package.scala:58)
	at GlueApp$.main(pc-spark-scala-script-test-1.scala:83)
	at GlueApp.main(pc-spark-scala-script-test-1.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.amazonaws.services.glue.SparkProcessLauncherPlugin.invoke(ProcessLauncher.scala:48)
	at com.amazonaws.services.glue.SparkProcessLauncherPlugin.invoke$(ProcessLauncher.scala:48)
	at com.amazonaws.services.glue.ProcessLauncher$$anon$1.invoke(ProcessLauncher.scala:78)
	at com.amazonaws.services.glue.ProcessLauncher.launch(ProcessLauncher.scala:143)
	at com.amazonaws.services.glue.ProcessLauncher$.main(ProcessLauncher.scala:30)
	at com.amazonaws.services.glue.ProcessLauncher.main(ProcessLauncher.scala)
Caused by: org.opensearch.hadoop.OpenSearchHadoopIllegalArgumentException: Unsupported/Unknown OpenSearch version [7.10.2].Highest supported version is [3.x]. You may need to upgrade OpenSearch-Hadoop.
	at org.opensearch.hadoop.util.OpenSearchMajorVersion.parse(OpenSearchMajorVersion.java:91)
	at org.opensearch.hadoop.rest.RestClient.mainInfo(RestClient.java:707)
	at org.opensearch.hadoop.rest.InitializationUtils.discoverClusterInfo(InitializationUtils.java:430)
	... 15 more`

However when I disable the compatibility it using below request, it works. 
`--header 'Content-Type: application/json'  -d '{
   "persistent" : {
     "compatibility.override_main_response_version" : false
   }
 }'
`

It works because now my response from ES for cluster info returns 

`{
  "name" : "----",
  "cluster_name" : "----",
  "cluster_uuid" : "----",
  "version" : {
    "distribution" : "opensearch",
    "number" : "2.3.0",
    "build_type" : "tar",
    "build_hash" : "unknown",
    "build_date" : "2022-11-10T22:04:34.357368Z",
    "build_snapshot" : false,
    "lucene_version" : "9.3.0",
    "minimum_wire_compatibility_version" : "7.10.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
`

Should it work irrespective of compatibility mode for AWS OpenSearch?

Note: I understand this library is not made to work for AWS OpenSearch only.

**Comment by prashantsc** [comment]
Please let me know if you think this should be an enhancement.

**Comment by harshavamsi** [comment]
Hi, the main branch and the 2.0 branch both support only opensearch version > 2. The 1.0 branch supports OpenSearch > 1.0 and ES version 7.10. That's why turning on/off the compatibility mode affects the outcome. If you want to use this library with OpenSearch, you don't need compatibility mode.
