### ISSUE TITLE
[BUG] Get OpenSearchHadoopIllegalArgumentException when connect to AWS OpenSearch 2.3 domain.

### ISSUE THREAD

**Issue by penghuo** [opensearch-project/opensearch-hadoop#181]
### What is the bug?

```
23/04/14 10:04:54 ERROR NetworkClient: Node [https://domain.us-west-2.es.amazonaws.com:9200] failed (java.net.SocketTimeoutException: connect timed out); no other nodes left - aborting...
org.opensearch.hadoop.OpenSearchHadoopIllegalArgumentException: Cannot detect OpenSearch version - typically this happens if the network/OpenSearch cluster is not accessible or when targeting a WAN/Cloud instance without the proper setting 'opensearch.nodes.wan.only'
  at org.opensearch.hadoop.rest.InitializationUtils.discoverClusterInfo(InitializationUtils.java:440)
  at org.opensearch.spark.sql.OpenSearchSparkSQL$.saveToOpenSearch(OpenSearchSparkSQL.scala:109)
  at org.opensearch.spark.sql.OpenSearchSparkSQL$.saveToOpenSearch(OpenSearchSparkSQL.scala:94)
  at org.opensearch.spark.sql.package$SparkDataFrameFunctions.saveToOpenSearch(package.scala:59)
  ... 51 elided
Caused by: org.opensearch.hadoop.rest.OpenSearchHadoopNoNodesLeftException: Connection error (check network and/or proxy settings)- all nodes failed; tried [[https://domain.us-west-2.es.amazonaws.com:9200]]
  at org.opensearch.hadoop.rest.NetworkClient.execute(NetworkClient.java:170)
  at org.opensearch.hadoop.rest.RestClient.execute(RestClient.java:433)
  at org.opensearch.hadoop.rest.RestClient.execute(RestClient.java:429)
  at org.opensearch.hadoop.rest.RestClient.execute(RestClient.java:397)
  at org.opensearch.hadoop.rest.RestClient.mainInfo(RestClient.java:694)
  at org.opensearch.hadoop.rest.InitializationUtils.discoverClusterInfo(InitializationUtils.java:430)
  ... 54 more
```

### How can one reproduce the bug?
* Use spark-shell
```
spark-3.1.2-bin-hadoop3.2  bin/spark-shell \
  --jars /opensearch-hadoop/spark/sql-30/build/libs/opensearch-spark-30_2.12-3.0.0-SNAPSHOT.jar
```

* Write to OpenSearch Index.
```
import org.apache.spark.sql.SQLContext
import org.apache.spark.sql.SQLContext._
import org.opensearch.spark.sql._

val sql = new SQLContext(sc)

val accountsRead = sql.read.json("/tmp/accounts.json")
val options = Map("pushdown" -> "true",     
"opensearch.nodes" -> "https://domain.us-west-2.es.amazonaws.com", 
"opensearch.aws.sigv4.enabled" -> "true",
"opensearch.aws.sigv4.region" -> "us-west-2",
"opensearch.nodes.resolve.hostname" -> "false",
"opensearch.nodes.wan.only" -> "true",
"opensearch.net.ssl" -> "true")   
accountsRead.saveToOpenSearch("accounts-00001", options)
```

### What is the expected behavior?
1. alt1, update the user doc, clearly define what is the expected value of `opensearch.nodes`.
2. alt2, add another setting to cover the AWS OpenSearch domain use case, which acctually not `nodes`.

### What is your host/environment?
* spark-3.1.2-bin-hadoop3.2

### Do you have any additional context?
change the "opensearch.nodes" to "https://domain.us-west-2.es.amazonaws.com:443" could solve the problem.

**Comment by harshavamsi** [comment]
Hi @penghuo, thanks for bringing this up.

So, `opensearch.port` is a setting that you could use to set the default port. I think maybe the docs don't make it clear enough that is is required. Happy to update the docs to clearly indicate that.
