### ISSUE TITLE
Add support for Amazon OpenSearch Serverless

### ISSUE THREAD

**Issue by sameercaresu** [opensearch-project/opensearch-hadoop#269]
### Is your feature request related to a problem?
I am trying to connect to Opensearch serverless collection from databrikcs. I can connect to Opensearch managed cluster using this. However, while trying to connect to serverless collection, I keep getting this error
`OpenSearchHadoopIllegalArgumentException: Cannot detect OpenSearch version - typically this happens if the network/OpenSearch cluster is not accessible or when targeting a WAN/Cloud instance without the proper setting 'opensearch.nodes.wan.only'
Caused by: OpenSearchHadoopNoNodesLeftException: Connection error (check network and/or proxy settings)- all nodes failed; tried [[https://xxx.aoss.amazonaws.com:9200`

I have tried following configuration
`"pushdown" -> "true",
  "opensearch.nodes" -> "https://xxx.aoss.amazonaws.com",
  "opensearch.nodes.wan.only" -> "true",
  "opensearch.aws.sigv4.region" -> "us-east-1",
  "opensearch.aws.sigv4.service.name" -> "aoss",
  "opensearch.aws.sigv4.enabled" -> "true"`
  
### What solution would you like?
Is it already possible to connect to Opensearch serverless? If yes, then could you please point me to correct set of configuration? If not, then I would like to request this feature.

### What alternatives have you considered?
I used elasticsearch hadoop, but that doesn't work either with Opensearch serverless.

### Do you have any additional context?
No.

**Comment by ktech-rob** [comment]
Hi, 
Just ran into the same issue as @sameercaresu. @harshavamsi I was wondering if there had been any update on this?

**Comment by wbeckler** [comment]
I haven't heard of any changes to Serverless to address this API gap.

**Comment by eswar7216** [comment]
We have a usecase to connect to open search serverless from Apache spark. I am running into similar issue as well. Is there a workaround to connect to open search serverless from Apache spark ?

**Comment by wbeckler** [comment]
There is still no known workaround. If you do figure out a way, please share it here or propose a PR so we can patch the client.

**Comment by eswar7216** [comment]
Not sure if everyone is doing the same as what I was trying to do but it works for me.
I have data in database which I was trying to get it into openSearch using apache spark in EMR.
Database -> EMR(Saprk) -> OpenSearch serverless.

I am using opensearch-hadoop(java) to connect to openSearch serverless (this is deployed in VPC) using a vpc endpooint something below and it works for me,

```
Map<String, String> map = new HashMap<>();
map.put("opensearch.nodes", "vpc domain url");
map.put("opensearch.port", "443");
map.put("opensearch.resource", "index_name");
map.put("opensearch.nodes.wan.only", "true");

//data here is which I read from database
JavaOpenSearchSparkSQL.saveToOpenSearch(data, map);
```

**Comment by Xtansia** [comment]
I've done some quick investigation into this and it's more extensive than just the `/` info request.
The first few missing APIs I hit while trying to do a simple write from spark can be worked around, though not ideally:
- `GET /` - can be hardcoded to return a dummy info if targeting serverless.
- `GET /_cluster/health/{index}` - can be hardcoded to GREEN if serverless
- `POST /{index}/_refresh` - can be NOOP if serverless

The bigger issue I then hit trying to do a read:
- `GET /{index}/_search_shards` which is used to determine partitions for reading and serverless doesn't support shard information

**Comment by Xtansia** [comment]
> @Xtansia It looks like _search_shards is getting called even when the setting os.nodes.client.only is set to TRUE. In that scenario the _search_shards is useless and shouldn't execute since no shards will map to non-data nodes. That means this should be a noop:
> 
> https://github.com/opensearch-project/opensearch-hadoop/blob/c9a6a1cb11404d2e738bbe57cc724609f3020e7f/mr/src/main/java/org/opensearch/hadoop/rest/RestRepository.java#L279
> 
> . Thoughts?

It's not quite as simple as just not calling it, as it uses the shards to determine how to partition the job within Spark for parallelisation. Serverless doesn't expose any shard information. It may be possible to workaround and hard code 1 or a configurable number of partitions for serverless, but I have dug into it far enough to know if that's feasible if other parts of the code expect to use an actual shard ID

**Comment by itiyama** [comment]
@Xtansia How does Hadoop client use the following APIs? I am exploring a solution to support some dummy/empty response for these APIs in serverless to support backward compatibility. But without understanding how the client uses these APIs, returning dummy response would be of no use.

1. `GET /` - what does it do with the response? Let's say serverless deployment returns empty response for all fields or some dummy value? Would that work?
2. `GET /_cluster/health/{index}` - we can hard code this to GREEN, are there any other response params that the client relies on?
3. `POST /{index}/_refresh` - yes, this can be NOOP.

**Comment by Leo-Rola** [comment]
@dblock i have seen you pinned this issue about using hadoop with opensearch serverless. Can I ask what have you solved? if for example I want to use glue to transfer documents from a collection OpenSearch Serverless to another, now could I do that? Thanks in advance

**Comment by vigneshvrt** [comment]
I found this workaround, and it works for me. I hardcoded the cluster name and version.

`SparkConf     
 .set("opensearch.internal.opensearch.version", "7.10")
 .set("opensearch.internal.opensearch.cluster.name", "<cluster_name>")
.set("opensearch.internal.opensearch.cluster.uuid", "")
`

**Comment by ken2190** [comment]
Hello guys. I have same issue like him when using this connection option config on glue job notebook. I create iam role with OpenSearchConsoleFullAccess and then i set this IAM ARN as master user in Fine-grained access control [security configuration - opensearch domain]
I'm using Glue 4.0 - Supports spark 3.3, Scala 2, Python 3 for glue notebook job

Here is the setting inside glue job notebook
# Set the idle timeout, Glue version, worker type, and number of workers
%idle_timeout 2880
%glue_version 4.0
%worker_type G.1X
%number_of_workers 10

# Spark Config
%extra_jars <s3bucket>/mybucket/opensearch-spark-30_2.12-1.3.0.jar
%spark_conf spark.jars.packages=org.opensearch:opensearch-spark-30_2.12:1.3.0
.......

            connection_options={
                "connectionName": "opensearch",
                "opensearch.resource": "my_index",
                "pushdown": "true",
                "opensearch.nodes": "https://opensearch-cluster",
                "opensearch.port": "443",
                "opensearch.nodes.resolve.hostname": "false",
                "opensearch.nodes.wan.only": "true",
                "opensearch.net.ssl" : "true",
                "opensearch.aws.sigv4.enabled": "true",
                "opensearch.aws.sigv4.region": "my-region"
            }

 MyTransform(glueContext, dynamic_frame)
```
Error writing to DynamoDB: An error occurred while calling o1293.pyWriteDynamicFrame.
: org.opensearch.hadoop.OpenSearchHadoopIllegalArgumentException: Cannot detect OpenSearch version - typically this happens if the network/OpenSearch cluster is not accessible or when targeting a WAN/Cloud instance without the proper setting 'opensearch.nodes.wan.only'
	at org.opensearch.hadoop.rest.InitializationUtils.discoverClusterInfo(InitializationUtils.java:423)
	at org.opensearch.spark.sql.OpenSearchSparkSQL$.saveToOpenSearch(OpenSearchSparkSQL.scala:109)
	at org.opensearch.spark.sql.OpenSearchRelation.insert(DefaultSource.scala:563)
	at org.opensearch.spark.sql.DefaultSource.createRelation(DefaultSource.scala:106)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:45)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:75)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:73)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:84)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:103)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:107)
	at org.apache.spark.sql.execution.SQLExecution$.withTracker(SQLExecution.scala:224)
	at org.apache.spark.sql.execution.SQLExecution$.executeQuery$1(SQLExecution.scala:114)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$7(SQLExecution.scala:139)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:107)
	at org.apache.spark.sql.execution.SQLExecution$.withTracker(SQLExecution.scala:224)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:139)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:245)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:138)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:68)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:100)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:96)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:615)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:177)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:615)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:591)
	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:96)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:83)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:81)
	at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:124)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:860)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:390)
	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:363)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:247)
	at com.amazonaws.services.glue.SparkSQLDataSink.$anonfun$writeDynamicFrame$3(DataSink.scala:673)
	at com.amazonaws.services.glue.SparkSQLDataSink.$anonfun$writeDynamicFrame$3$adapted(DataSink.scala:660)
	at com.amazonaws.services.glue.util.FileSchemeWrapper.$anonfun$executeWithQualifiedScheme$1(FileSchemeWrapper.scala:105)
	at com.amazonaws.services.glue.util.FileSchemeWrapper.executeWith(FileSchemeWrapper.scala:96)
	at com.amazonaws.services.glue.util.FileSchemeWrapper.executeWithQualifiedScheme(FileSchemeWrapper.scala:105)
	at com.amazonaws.services.glue.SparkSQLDataSink.writeDynamicFrame(DataSink.scala:660)
	at com.amazonaws.services.glue.DataSink.pyWriteDynamicFrame(DataSink.scala:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.opensearch.hadoop.rest.OpenSearchHadoopInvalidRequest: [GET] on [] failed; server[[https://oepnsearch-cluster:443](https://opensearch-cluster/)] returned [403|Forbidden]
	at org.opensearch.hadoop.rest.RestClient.checkResponse(RestClient.java:489)
	at org.opensearch.hadoop.rest.RestClient.execute(RestClient.java:445)
	at org.opensearch.hadoop.rest.RestClient.execute(RestClient.java:439)
	at org.opensearch.hadoop.rest.RestClient.execute(RestClient.java:407)
	at org.opensearch.hadoop.rest.RestClient.mainInfo(RestClient.java:720)
	at org.opensearch.hadoop.rest.InitializationUtils.discoverClusterInfo(InitializationUtils.java:413)
	... 56 more
Caused by: org.opensearch.hadoop.rest.OpenSearchHadoopRemoteException: security_exception: no permissions for [cluster:monitor/main] and User [name=arn:aws:iam::791787295069:role/dynamoDB_demo, backend_roles=[arn:aws:iam::791787295069:role/dynamoDB_demo], requestedTenant=null]
	at org.opensearch.hadoop.rest.ErrorExtractor.extractErrorWithCause(ErrorExtractor.java:54)
	at org.opensearch.hadoop.rest.ErrorExtractor.extractError(ErrorExtractor.java:92)
	at org.opensearch.hadoop.rest.RestClient.checkResponse(RestClient.java:473)
	... 61 more
```

If i change to basic auth it worked without problem. (I must set master user and password instead of IAM ARN). Do you have any idea to update config if i want to use iam arn?
```
            connection_options={
                "connectionName": "opensearch",
                "opensearch.resource": "my_index",
                "pushdown": "true",
                "opensearch.nodes": "https://opensearch-cluster",
                "opensearch.port": "443",
                "opensearch.nodes.resolve.hostname": "false",
                "opensearch.nodes.wan.only": "true",
                "opensearch.net.ssl" : "true",
                "opensearch.net.http.auth.user": "user",
                "opensearch.net.http.auth.pass": "pass",
            }
```

**Comment by lawofcycles** [comment]
Hi, I'm interested in contributing support for OpenSearch Serverless in opensearch-hadoop. I will try to properly map the Serverless API interface. Once I have a concrete implementation plan, I'll share more details.
