### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by manirudh78** [opensearch-project/opensearch-hadoop#80]
### What is the bug?
When we 

### How can one reproduce the bug?
Step 1: use the jar opensearch-hadoop-3.0.0-SNAPSHOT.jar after building the git repo for opensearch-hadoop with java_home set to jdk 14 and running ./gradlew assemble

Step 2:  Access the jar from /dist/buil/libs/opensearch-hadoop-3.0.0-SNAPSHOT.jar

Step 3: Install opensearch docker with below steps:
docker pull opensearchproject/opensearch:latest
docker run -d -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" opensearchproject/opensearch:latest

Check connection to opensearch using this:
curl https://localhost:9200 -ku 'admin:admin'

The output should be:
curl https://localhost:9200 -ku 'admin:admin'
{
  "name" : "37e3f842cf8b",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "4h19brhYRLqOy3uMMjS7Rg",
  "version" : {
    "distribution" : "opensearch",
    "number" : "2.5.0",
    "build_type" : "tar",
    "build_hash" : "b8a8b6c4d7fc7a7e32eb2cb68ecad8057a4636ad",
    "build_date" : "2023-01-18T23:49:00.584806002Z",
    "build_snapshot" : false,
    "lucene_version" : "9.4.2",
    "minimum_wire_compatibility_version" : "7.10.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}

Step 4: Now use the jar and the scala code to write some data to the local docker opensearch
import org.apache.spark.sql.SparkSession
import org.opensearch.spark.sql._

object ScalaSparkTestApp extends App {

  val spark = SparkSession.builder()
    .master("local[*]")
    .config("spark.jars","jar/opensearch-hadoop-3.0.0-SNAPSHOT.jar")
    .getOrCreate()

  var df = spark.read.json("resources/part-00000-4e0547fd-a31e-4b86-bb79-74aff317f378-c000.json")

  // write to opensearch
  val cfg = Map("opensearch.nodes" -> "https://localhost",  "opensearch.username" -> "admin",
    "opensearch.password" -> "admin","opensearch.net.ssl" -> "true" ,"opensearch.nodes.wan.only" -> "true")
  df.saveToOpenSearch("test_scala_write")
}

### What is the expected behavior?
It should have written data to opensearch

### What is your host/environment?
Macos

### Error Message:
23/02/13 11:21:39 ERROR NetworkClient: Node [127.0.0.1:9200] failed (org.opensearch.hadoop.thirdparty.apache.commons.httpclient.NoHttpResponseException: The server 127.0.0.1 failed to respond); no other nodes left - aborting...
Exception in thread "main" org.opensearch.hadoop.OpenSearchHadoopIllegalArgumentException: Cannot detect OpenSearch version - typically this happens if the network/OpenSearch cluster is not accessible or when targeting a WAN/Cloud instance without the proper setting 'opensearch.nodes.wan.only'
	at org.opensearch.hadoop.rest.InitializationUtils.discoverClusterInfo(InitializationUtils.java:440)
	at org.opensearch.spark.sql.OpenSearchSparkSQL$.saveToOpenSearch(OpenSearchSparkSQL.scala:109)
	at org.opensearch.spark.sql.OpenSearchSparkSQL$.saveToOpenSearch(OpenSearchSparkSQL.scala:91)
	at org.opensearch.spark.sql.package$SparkDataFrameFunctions.saveToOpenSearch(package.scala:58)
	at ScalaSparkTestApp$.delayedEndpoint$ScalaSparkTestApp$1(ScalaSparkTestApp.scala:16)
	at ScalaSparkTestApp$delayedInit$body.apply(ScalaSparkTestApp.scala:4)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at ScalaSparkTestApp$.main(ScalaSparkTestApp.scala:4)
	at ScalaSparkTestApp.main(ScalaSparkTestApp.scala)
Caused by: org.opensearch.hadoop.rest.OpenSearchHadoopNoNodesLeftException: Connection error (check network and/or proxy settings)- all nodes failed; tried [[127.0.0.1:9200]] 
	at org.opensearch.hadoop.rest.NetworkClient.execute(NetworkClient.java:170)
	at org.opensearch.hadoop.rest.RestClient.execute(RestClient.java:433)
	at org.opensearch.hadoop.rest.RestClient.execute(RestClient.java:429)
	at org.opensearch.hadoop.rest.RestClient.execute(RestClient.java:397)
	at org.opensearch.hadoop.rest.RestClient.mainInfo(RestClient.java:694)
	at org.opensearch.hadoop.rest.InitializationUtils.discoverClusterInfo(InitializationUtils.java:430)
	... 14 more

**Comment by nknize** [comment]
Can you check your docker log? Do you see something like this:

```
[2023-02-16T21:39:00,581][WARN ][o.o.h.AbstractHttpServerTransport] [0eaac7844e5f] caught exception while handling client http traffic, closing connection Netty4HttpChannel{localAddress=/240.10.0.2:9200, remoteAddress=/240.10.0.1:47556}
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:499) ~[netty-codec-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.86.Final.jar:4.1.86.Final]
...
```

If so, try adding the following property to your cfg map: `"opensearch.net.ssl.cert.allow.self.signed" -> "true"`

**Comment by manirudh78** [comment]
Hello @nknize,
Tried adding the certificate true/false the error is still the same:

Exception in thread "main" org.opensearch.hadoop.OpenSearchHadoopIllegalArgumentException: Cannot detect OpenSearch version - typically this happens if the network/OpenSearch cluster is not accessible or when targeting a WAN/Cloud instance without the proper setting 'opensearch.nodes.wan.only'
	at org.opensearch.hadoop.rest.InitializationUtils.discoverClusterInfo(InitializationUtils.java:440)
	at org.opensearch.spark.sql.OpenSearchSparkSQL$.saveToOpenSearch(OpenSearchSparkSQL.scala:109)
	at org.opensearch.spark.sql.OpenSearchSparkSQL$.saveToOpenSearch(OpenSearchSparkSQL.scala:91)
	at org.opensearch.spark.sql.package$SparkDataFrameFunctions.saveToOpenSearch(package.scala:58)
	at ScalaSparkTestApp$.delayedEndpoint$ScalaSparkTestApp$1(ScalaSparkTestApp.scala:20)
	at ScalaSparkTestApp$delayedInit$body.apply(ScalaSparkTestApp.scala:6)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at ScalaSparkTestApp$.main(ScalaSparkTestApp.scala:6)
	at ScalaSparkTestApp.main(ScalaSparkTestApp.scala)
Caused by: org.opensearch.hadoop.rest.OpenSearchHadoopNoNodesLeftException: Connection error (check network and/or proxy settings)- all nodes failed; tried [[127.0.0.1:9200]] 
	at org.opensearch.hadoop.rest.NetworkClient.execute(NetworkClient.java:170)
	at org.opensearch.hadoop.rest.RestClient.execute(RestClient.java:433)
	at org.opensearch.hadoop.rest.RestClient.execute(RestClient.java:429)
	at org.opensearch.hadoop.rest.RestClient.execute(RestClient.java:397)
	at org.opensearch.hadoop.rest.RestClient.mainInfo(RestClient.java:694)
	at org.opensearch.hadoop.rest.InitializationUtils.discoverClusterInfo(InitializationUtils.java:430)
	... 14 more

**Comment by nknize** [comment]
It doesn't look like you're actually using the `cfg` object for anything. 

Try replacing your scala code with the following:

```scala
  val spark = SparkSession.builder().master("local[*]")
    .config("spark.jars","jar/opensearch-hadoop-3.0.0-SNAPSHOT.jar")
    .config("opensearch.nodes", "127.0.0.1").config("opensearch.net.http.auth.user", "admin").config("opensearch.net.http.auth.pass", "admin").config("opensearch.net.ssl", "true")
    .config("opensearch.net.ssl.cert.allow.self.signed", "true")
    .getOrCreate()

  // write to opensearch
  var df = spark.read.json("resources/part-00000-4e0547fd-a31e-4b86-bb79-74aff317f378-c000.json")
  df.saveToOpenSearch("test_scala_write")
```

You should see the app logs return the following:

```
23/02/16 23:13:10 INFO OpenSearchRDDWriter: Writing to [test_scala_write]
```

**Comment by nknize** [comment]
Another thing you could do is drop the `"spark.jars"` property and just use sbt.

Here's my simple test `build.sbt` (w/ some "version" stuff autogen by intellij)

```
ThisBuild / version := "0.1.0-SNAPSHOT"

ThisBuild / scalaVersion := "2.12.17"

lazy val root = (project in file("."))
  .settings(
    name := "OpenSearchHadoopScalaTest"
  )

libraryDependencies ++= Seq(
  "org.apache.spark" %% "spark-core" % "3.2.3" exclude("javax", "servlet") exclude("org.apache", "hadoop"),
  "org.opensearch" % "opensearch-hadoop" % "3.0.0-SNAPSHOT",
  "org.antlr" % "antlr4-runtime" % "4.3"
)

resolvers += Resolver.mavenCentral
resolvers += Resolver.mavenLocal
```

I did run into an issue where the `./gradlew publishToMavenLocal` threw a project name mismatch error (it expected the scala version in the jar but the project didn't include it).

So I manually installed the jar myself using:

`mvn install:install-file -Dfile=<path-to-opensearch-hadoop_jar> -DpomFile=<path-to-opensearch_hadoop_pomfile>`

**Comment by manirudh78** [comment]
Hello @nknize,

Thank you for your reply.

Even after using the spark config that you mentioned in your post the spark logs give this error:

3/02/17 10:04:12 INFO OpenSearchDataFrameWriter: Writing to [test_scala_write]
23/02/17 10:04:30 ERROR NetworkClient: Node [172.23.0.2:9200] failed (java.net.SocketTimeoutException: connect timed out); selected next node [172.23.0.4:9200]
23/02/17 10:04:48 ERROR NetworkClient: Node [172.23.0.4:9200] failed (java.net.SocketTimeoutException: connect timed out); no other nodes left - aborting...
23/02/17 10:04:48 ERROR Executor: Exception in task 0.0 in stage 2.0 (TID 20)
org.opensearch.hadoop.rest.OpenSearchHadoopNoNodesLeftException: Connection error (check network and/or proxy settings)- all nodes failed; tried [[172.23.0.2:9200, 172.23.0.4:9200]] 
	at org.opensearch.hadoop.rest.NetworkClient.execute(NetworkClient.java:170)
	at org.opensearch.hadoop.rest.RestClient.execute(RestClient.java:433)
	at org.opensearch.hadoop.rest.RestClient.execute(RestClient.java:429)
	at org.opensearch.hadoop.rest.RestClient.execute(RestClient.java:389)
	at org.opensearch.hadoop.rest.RestClient.execute(RestClient.java:393)
	at org.opensearch.hadoop.rest.RestClient.get(RestClient.java:179)
	at org.opensearch.hadoop.rest.request.GetAliasesRequestBuilder.execute(GetAliasesRequestBuilder.java:78)
	at org.opensearch.hadoop.rest.RestService.createWriter(RestService.java:625)
	at org.opensearch.spark.rdd.OpenSearchRDDWriter.write(OpenSearchRDDWriter.scala:77)
	at org.opensearch.spark.sql.OpenSearchSparkSQL$$anonfun$saveToOpenSearch$1.apply(OpenSearchSparkSQL.scala:113)
	at org.opensearch.spark.sql.OpenSearchSparkSQL$$anonfun$saveToOpenSearch$1.apply(OpenSearchSparkSQL.scala:113)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
23/02/17 10:04:48 WARN TaskSetManager: Lost task 0.0 in stage 2.0 (TID 20) (142.133.8.239 executor driver): org.opensearch.hadoop.rest.OpenSearchHadoopNoNodesLeftException: Connection error (check network and/or proxy settings)- all nodes failed; tried [[172.23.0.2:9200, 172.23.0.4:9200]] 
	at org.opensearch.hadoop.rest.NetworkClient.execute(NetworkClient.java:170)
	at org.opensearch.hadoop.rest.RestClient.execute(RestClient.java:433)
	at org.opensearch.hadoop.rest.RestClient.execute(RestClient.java:429)
	at org.opensearch.hadoop.rest.RestClient.execute(RestClient.java:389)
	at org.opensearch.hadoop.rest.RestClient.execute(RestClient.java:393)
	at org.opensearch.hadoop.rest.RestClient.get(RestClient.java:179)
	at org.opensearch.hadoop.rest.request.GetAliasesRequestBuilder.execute(GetAliasesRequestBuilder.java:78)
	at org.opensearch.hadoop.rest.RestService.createWriter(RestService.java:625)
	at org.opensearch.spark.rdd.OpenSearchRDDWriter.write(OpenSearchRDDWriter.scala:77)
	at org.opensearch.spark.sql.OpenSearchSparkSQL$$anonfun$saveToOpenSearch$1.apply(OpenSearchSparkSQL.scala:113)
	at org.opensearch.spark.sql.OpenSearchSparkSQL$$anonfun$saveToOpenSearch$1.apply(OpenSearchSparkSQL.scala:113)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

23/02/17 10:04:48 ERROR TaskSetManager: Task 0 in stage 2.0 failed 1 times; aborting job
23/02/17 10:04:48 INFO TaskSchedulerImpl: Removed TaskSet 2.0, whose tasks have all completed, from pool 
23/02/17 10:04:48 INFO TaskSchedulerImpl: Cancelling stage 2
23/02/17 10:04:48 INFO TaskSchedulerImpl: Killing all running tasks in stage 2: Stage cancelled
23/02/17 10:04:48 INFO DAGScheduler: ResultStage 2 (runJob at OpenSearchSparkSQL.scala:113) failed in 37.531 s due to Job aborted due to stage failure: Task 0 in stage 2.0 failed 1 times, most recent failure: Lost task 0.0 in stage 2.0 (TID 20) (142.133.8.239 executor driver): org.opensearch.hadoop.rest.OpenSearchHadoopNoNodesLeftException: Connection error (check network and/or proxy settings)- all nodes failed; tried [[172.23.0.2:9200, 172.23.0.4:9200]] 
	at org.opensearch.hadoop.rest.NetworkClient.execute(NetworkClient.java:170)
	at org.opensearch.hadoop.rest.RestClient.execute(RestClient.java:433)
	at org.opensearch.hadoop.rest.RestClient.execute(RestClient.java:429)
	at org.opensearch.hadoop.rest.RestClient.execute(RestClient.java:389)
	at org.opensearch.hadoop.rest.RestClient.execute(RestClient.java:393)
	at org.opensearch.hadoop.rest.RestClient.get(RestClient.java:179)
	at org.opensearch.hadoop.rest.request.GetAliasesRequestBuilder.execute(GetAliasesRequestBuilder.java:78)
	at org.opensearch.hadoop.rest.RestService.createWriter(RestService.java:625)
	at org.opensearch.spark.rdd.OpenSearchRDDWriter.write(OpenSearchRDDWriter.scala:77)
	at org.opensearch.spark.sql.OpenSearchSparkSQL$$anonfun$saveToOpenSearch$1.apply(OpenSearchSparkSQL.scala:113)
	at org.opensearch.spark.sql.OpenSearchSparkSQL$$anonfun$saveToOpenSearch$1.apply(OpenSearchSparkSQL.scala:113)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)


And the docker logs for opensearch has no error as why this is happening:


[2023-02-17T15:04:06,315][INFO ][o.o.j.s.JobSweeper       ] [opensearch-node1] Running full sweep





[2023-02-17T15:09:06,318][INFO ][o.o.j.s.JobSweeper       ] [opensearch-node1] Running full sweep
[2023-02-17T15:14:06,342][INFO ][o.o.j.s.JobSweeper       ] [opensearch-node1] Running full sweep
[2023-02-17T15:19:06,348][INFO ][o.o.j.s.JobSweeper       ] [opensearch-node1] Running full sweep
[2023-02-17T15:24:06,351][INFO ][o.o.j.s.JobSweeper       ] [opensearch-node1] Running full sweep
[2023-02-17T15:29:06,308][INFO ][o.o.j.s.JobSweeper       ] [opensearch-node1] Running full sweep
[2023-02-17T15:34:06,307][INFO ][o.o.j.s.JobSweeper       ] [opensearch-node1] Running full sweep
[2023-02-17T15:39:06,310][INFO ][o.o.j.s.JobSweeper       ] [opensearch-node1] Running full sweep
[2023-02-17T15:44:06,313][INFO ][o.o.j.s.JobSweeper       ] [opensearch-node1] Running full sweep
[2023-02-17T15:49:06,313][INFO ][o.o.j.s.JobSweeper       ] [opensearch-node1] Running full sweep
[2023-02-17T15:54:06,315][INFO ][o.o.j.s.JobSweeper       ] [opensearch-node1] Running full sweep
[2023-02-17T15:59:05,812][INFO ][o.o.a.t.CronTransportAction] [opensearch-node1] Start running AD hourly cron.
[2023-02-17T15:59:05,815][INFO ][o.o.a.t.ADTaskManager    ] [opensearch-node1] Start to maintain running historical tasks
[2023-02-17T15:59:06,343][INFO ][o.o.j.s.JobSweeper       ] [opensearch-node1] Running full sweep
[2023-02-17T16:04:06,348][INFO ][o.o.j.s.JobSweeper       ] [opensearch-node1] Running full sweep
[2023-02-17T16:09:06,353][INFO ][o.o.j.s.JobSweeper       ] [opensearch-node1] Running full sweep
[2023-02-17T16:42:12,830][INFO ][o.o.j.s.JobSweeper       ] [opensearch-node1] Running full sweep
[2023-02-17T16:47:12,836][INFO ][o.o.j.s.JobSweeper       ] [opensearch-node1] Running full sweep

**Comment by nknize** [comment]
Can you verify this docker command worked for you?

`docker run --name opensearch -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" opensearchproject/opensearch:2.5.0`

Also the following scala code:

```scala
  val spark = SparkSession.builder().master("local[*]")
    .config("opensearch.nodes", "127.0.0.1").config("opensearch.net.http.auth.user", "admin").config("opensearch.net.http.auth.pass", "admin").config("opensearch.net.ssl", "true")
    .config("opensearch.batch.size.bytes", "1kb").config("opensearch.net.ssl.cert.allow.self.signed", "true")
    .getOrCreate()

  var df = spark.read.option("multiline","true").json("resources/part-00000-4e0547fd-a31e-4b86-bb79-74aff317f378-c000.json")
  df.saveToOpenSearch("test_scala_write")
```

You should see the following OpenSearch log output:

```
23/02/17 14:09:56 INFO Executor: Running task 0.0 in stage 1.0 (TID 1)
23/02/17 14:09:56 INFO CodeGenerator: Code generated in 184.658739 ms
23/02/17 14:09:56 INFO OpenSearchDataFrameWriter: Writing to [test_scala_write]
```

**Comment by manirudh78** [comment]
Thanks @nknize the current jar supports 2.5.0
